source 'https://github.com/CocoaPods/Specs.git'

!use_frameworks!

platform :ios, '8.0'

pod 'DATAStack'

# Categories
pod 'NSJSONSerialization-ANDYJSONFile'
pod 'NSManagedObject-HYPPropertyMapper'
pod 'DATAFilter'
pod 'NSDictionary-ANDYSafeValue'
