use_frameworks!

platform :ios, '8.0'

pod 'DATAFilter'
pod 'DATAStack'
pod 'NSDictionary-ANDYSafeValue'
pod 'NSEntityDescription-SYNCPrimaryKey'
pod 'NSJSONSerialization-ANDYJSONFile'
pod 'NSManagedObject-HYPPropertyMapper'
pod 'SwiftRecord'
