fastlane_version "2.62.1"

default_platform :ios
  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: 'iOSTests',
      project: "Project.xcodeproj",
      devices: ["iPhone X"]
    )
end
