fastlane_version "2.62.1"

default_platform :ios

platform :ios do
  before_all do
   ENV['FL_BUILD_NUMBER_PROJECT'] = "Project.xcodeproj"
   ENV['SCAN_DEVICE'] = "Project.xcodeproj"
   ensure_git_status_clean unless ENV['FL_NO_ENSURE_CLEAN']
end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: 'iOSTests',
      project: "Project.xcodeproj",
      devices: ["iPhone X"]
    )
  end
end
