platform :ios, '7.0'

pod 'ANDYDataManager'
pod 'ANDYFetchedResultsTableDataSource'

# Categories
pod 'NSJSONSerialization-ANDYJSONFile'
pod 'NSManagedObject-HYPPropertyMapper', :git => 'https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper.git'
pod 'NSManagedObject-ANDYMapChanges'
