source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'ANDYDataManager'
pod 'ANDYFetchedResultsTableDataSource'

# Categories
pod 'NSJSONSerialization-ANDYJSONFile'
pod 'NSManagedObject-HYPPropertyMapper', :git => "https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper.git", :branch => "feature/reserved-words"
pod 'NSManagedObject-ANDYMapChanges'
pod 'NSDictionary-ANDYSafeValue'
